#!/bin/bash
source ~/command/common

_path="../../project"
_file=""
_list_=(
	../react-scripts/config/paths.js
	../react-scripts/config/webpack.config.dev.js
)

function checkUpdate()
{
	file=$(basename $1);
	if [ -e modify/${file} ]
	then
		diffmerge.sh modify/${file} ${_path}/node_modules/react-native/$1
		# diffmerge.sh ${_path}/node_modules/react-native/$1 origin/${file}
	else
		tmp=$1
		dir=${tmp:23}
	   diffmerge.sh modify/${dir%%/*}/${file} ${_path}/node_modules/react-native/$1
	#    diffmerge.sh ${_path}/node_modules/react-native/$1 origin/${dir%%/*}/${file}
	fi

}

function show_help()
{
	local -a list
	list="help"
	list=("${list[@]}" "Usage :checkUpdate [OPTIONS]")
	list=("${list[@]}" "  -p [path] :set the project path [~/xxx/project]")
	list=("${list[@]}" "  -f [file] :diff file")
	list=("${list[@]}" "  -h :show help ")
	__msgbox "${list[@]}"
}

function main()
{
	while getopts :p:f:h opt;do
		case $opt in
			p)_path="$OPTARG";;
			f)_file="$OPTARG";;
			h)show_help;exit;;
			*)show_help;exit;;
		esac
	done
	if [ "$_file" = "" ];then
		__radiobox "checkUpdate $_TARGET_" "no" "checkUpdate" "select bellow files to check"
	else
		diffmerge.sh ../../project/${_file} ${_path}/${_file}
	fi
}

main "$@"
