#!/bin/bash
source ~/command/common

_path="../../project"
_file=""
_list_=(
	react-scripts/config/paths.js
	react-scripts/config/webpack.config.dev.js
)

function checkUpdate()
{
	diffmerge.sh modify/$1 ${_path}/node_modules/$1
}

function show_help()
{
	local -a list
	list="help"
	list=("${list[@]}" "Usage :checkUpdate [OPTIONS]")
	list=("${list[@]}" "  -p [path] :set the project path [~/xxx/project]")
	list=("${list[@]}" "  -h :show help ")
	__msgbox "${list[@]}"
}

function main()
{
	while getopts :p:f:h opt;do
		case $opt in
			p)_path="$OPTARG";;
			h)show_help;exit;;
			*)show_help;exit;;
		esac
	done
	__radiobox "checkUpdate $_TARGET_" "no" "checkUpdate" "select bellow files to check"
}

main "$@"
